<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0-windows;net10.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <DebugType>embedded</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AnimeStudio.Utility\AnimeStudio.Utility.csproj" />
  </ItemGroup>
</Project>
